services:
  postgres:
    container_name: postgres
    image: nicoardizzoli/postgres:prueba-tecnica-banco
    environment:
      POSTGRES_USER: nicoardizzoli
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


#  prueba-tecnica-banco:
#    image: nicoardizzoli/prueba-tecnica-banco:0.0.1-SNAPSHOT
#    container_name: prueba-tecnica-banco
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
---

