application:
  title: TECHNICAL INTERVIEW - BANK
  version: 0.0.1

server:
  port: 8080
spring:
  application:
    name: technical-interview-bank
  datasource:
    url: jdbc:postgresql://postgres:5432/technical-interview-bank
    username: 'nicoardizzoli'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

api:
  throwable-in-custom-exception: false